name: Build Windows App

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt
          pip install torch==2.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Clean build dirs
        run: |
          rmdir /S /Q build || exit 0
          rmdir /S /Q dist  || exit 0

      - name: Build with PyInstaller
        run: pyinstaller egg_inspector.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EggInspector-windows
          path: dist/EggInspector/**
